class FoodKeywordGroups {
  FoodKeywordGroups._();

  static const Set<String> meat = {
    'beef',
    'pork',
    'lamb',
    'chicken',
    'duck',
    'turkey',
    'veal',
    'bacon',
    'ham',
    'sausage',
    'meat',
    'meatball',
    'prosciutto',
    'salami',
    'pepperoni',
    'steak',
    'mince',
    'rib',
    'brisket',
    'kebab',
    'kofta',
    'shawarma',
    'bulgogi',
    'chashu',
    'pancetta',
    'guanciale',
    'ragu',
    'chorizo',
    'gyros',
    'souvlaki',
    'tibs',
    'rendang',
    'picanha',
    'bolognese',
    'carnitas',
    'pulled pork',
    'char siu',
  };

  static const Set<String> shellfish = {
    'shrimp',
    'prawn',
    'crab',
    'lobster',
    'crayfish',
    'scallop',
    'clam',
    'mussel',
    'oyster',
    'squid',
    'calamari',
    'octopus',
    'gambas',
  };

  static const Set<String> fish = {
    'fish',
    'salmon',
    'tuna',
    'cod',
    'bass',
    'trout',
    'tilapia',
    'anchovy',
    'sardine',
    'halibut',
    'mackerel',
    'seafood',
    'eel',
    'nigiri',
    'sashimi',
    'bream',
    'ceviche',
  };

  static const Set<String> dairy = {
    'milk',
    'cream',
    'creamy',
    'cheese',
    'butter',
    'yogurt',
    'yoghurt',
    'mozzarella',
    'parmesan',
    'parmigiano',
    'cheddar',
    'gruyere',
    'gruyère',
    'bechamel',
    'béchamel',
    'mascarpone',
    'ghee',
    'feta',
    'burrata',
    'paneer',
    'ricotta',
    'gorgonzola',
    'pecorino',
    'custard',
    'labneh',
    'tzatziki',
    'raita',
    'lassi',
    'gelato',
  };

  static const Set<String> gluten = {
    'wheat',
    'flour',
    'bread',
    'pasta',
    'noodle',
    'dough',
    'batter',
    'crouton',
    'couscous',
    'semolina',
    'bulgur',
    'gluten',
    'baguette',
    'pita',
    'naan',
    'tortilla',
    'bun',
    'brioche',
    'focaccia',
    'ciabatta',
    'filo',
    'spaghetti',
    'penne',
    'linguine',
    'rigatoni',
    'tagliatelle',
    'lasagna',
    'lasagne',
    'ramen',
    'udon',
    'pancake',
    'waffle',
    'croissant',
    'toast',
    'breaded',
    'panko',
    'wrap',
    'pie',
    'cake',
    'pizza',
    'roll',
    'biscuit',
    'pastry',
    'gyoza',
    'samosa',
    'baklava',
    'churro',
    'tempura',
  };

  static const Set<String> legumes = {
    'bean',
    'lentil',
    'pea',
    'chickpea',
    'soy',
    'tofu',
    'tempeh',
    'hummus',
    'edamame',
    'falafel',
    'dal',
    'dahl',
    'miso',
  };

  static const Set<String> grains = {
    'rice',
    'pasta',
    'bread',
    'noodle',
    'grain',
    'oat',
    'wheat',
    'flour',
    'corn',
    'quinoa',
    'bulgur',
    'couscous',
    'barley',
  };

  static const Set<String> pork = {
    'pork',
    'bacon',
    'ham',
    'prosciutto',
    'lard',
    'pancetta',
    'guanciale',
    'chorizo',
    'pepperoni',
    'salami',
    'char siu',
    'chashu',
  };

  static const Set<String> alcohol = {
    'wine',
    'beer',
    'sake',
    'vodka',
    'cognac',
    'rum',
    'whisky',
    'whiskey',
    'bourbon',
    'cachaca',
    'cachaça',
    'liqueur',
    'brandy',
    'champagne',
    'caipirinha',
  };
}
